# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textnowapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ImageField(null=True, upload_to='textnowapp/archives/')),
                ('message', models.TextField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textnowapp.Chat')),
            ],
        ),
    ]
