# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textnowapp', '0003_auto_20171119_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='archive',
            field=models.ImageField(null=True, upload_to='textnowapp/media/'),
        ),
    ]
