# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textnowapp', '0007_msg_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='archive',
        ),
    ]
